# Generated by Django 5.2.10 on 2026-01-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='violations/')),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to='plates/')),
                ('helmet_detected', models.BooleanField()),
                ('vehicle_number', models.CharField(blank=True, max_length=15, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
