# Generated by Django 5.2.10 on 2026-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='location',
            field=models.CharField(default='Bhimavaram', max_length=100),
        ),
        migrations.AddField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
