# Generated by Django 5.2.10 on 2026-01-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_violation_location_violation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle_number',
            field=models.CharField(default='00000', max_length=15),
            preserve_default=False,
        ),
    ]
