# Generated by Django 5.2.10 on 2026-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_violation_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AddField(
            model_name='violation',
            name='latitude',
            field=models.FloatField(default=16.5449),
        ),
        migrations.AddField(
            model_name='violation',
            name='longitude',
            field=models.FloatField(default=81.5212),
        ),
        migrations.AlterField(
            model_name='violation',
            name='confidence',
            field=models.FloatField(blank=True, help_text='OCR confidence percentage', null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='helmet_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
