# Generated by Django 5.2.10 on 2026-01-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_violation_options_violation_latitude_and_more'),
        ('vehicles', '0002_vehicle_owner_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Helmet Violation', 'verbose_name_plural': 'Helmet Violations'},
        ),
        migrations.AddField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Linked automatically using OCR vehicle number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='helmet_detected',
            field=models.BooleanField(default=False, help_text='True = helmet worn, False = violation'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
