# Generated by Django 5.2.10 on 2026-01-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
        ('detection', '0002_violation_location_violation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='issued_date',
            new_name='issued_at',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='challan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='fine_amount',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='challan',
            name='violation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='detection.violation'),
        ),
    ]
