# Generated by Django 5.2.10 on 2026-01-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0002_rename_issued_date_challan_issued_at_and_more'),
        ('detection', '0003_alter_violation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='challan_number',
        ),
        migrations.AddField(
            model_name='challan',
            name='echallan_number',
            field=models.CharField(db_index=True, default='00000', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challan',
            name='fine_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='detection.violation'),
        ),
    ]
