# Generated by Django 5.2.10 on 2026-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=15, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_address', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
