# Generated by Django 5.2.10 on 2026-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_email',
            field=models.EmailField(default='00000', max_length=254),
            preserve_default=False,
        ),
    ]
